### PR TITLE
Create proper empty parquet when serializing from empty enumerable

### PR DESCRIPTION
**Pull request by qrczak0**
### Fixes
Properly serialized Enumerable.Empty<T> to empty parquet file.

### Description
When serializing Enumerable.Empty<T> to parquet generated file was corrupted and on deserialization resulted with exception: 
IOException: not a Parquet file (size too small)

- [x] I have included unit tests validating this fix.
- [ ] I have updated markdown documentation where required.
- [x] I understand that successful approval of my pull request requires reproducible tests as per [Contribution Guideline](https://github.com/elastacloud/parquet-dotnet/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by qrczak0** [comment]
Can you trigger remaining tests? I would like to use package from original source :)

**Comment by tkrzysteczko** [comment]
Reached same issue, thanks for fixing it. Is there a chance that it will be merged to master branch?

**Comment by aloneguid** [comment]
merged!

**Comment by tkrzysteczko** [comment]
Thank you!

**Pull request merged**
