### PR TITLE
DO NOT CLOSE!!!

### PR DESCRIPTION
**Pull request by aloneguid**
### Fixes

Issue #195 

### Description

Opened only to test CI (AppVeyor) with Python!!!!

### Todos
- [ ] unit/integration tests
- [ ] documentation

### CODE REVIEW

**Comment by xhochy** [comment]
@aloneguid Have a look at https://github.com/apache/arrow/blob/master/ci/msvc-build.bat#L37:L53 

Instead of specifying `six pytest setuptools numpy pandas cython thrift-cpp` in the last line, using `pyarrow` should suffice.

**Comment by aloneguid** [comment]
@xhochy I've got this working locally but unfortunately CI we use (AppVeyor) doesn't allow installing conda. Even if it would it takes a lot of time for CI to finish. I'm thinking of using Travis just for integration tests in addition to what we have now.

**Comment by xhochy** [comment]
> but unfortunately CI we use (AppVeyor) doesn't allow installing conda

That should work, we test using conda in AppVeyor for Apache Arrow. I'm not an expert of AppVeyor configurations though.

**Comment by aloneguid** [comment]
@xhochy you're correct, thank you! Turns out AppVeyor has Miniconda available https://www.appveyor.com/docs/build-environment/#miniconda - should make my life so much easier.

**Pull request closed without merging**
