### PR TITLE
Issue #336 Issue reading column with multiple DATA_PAGE encodings

### PR DESCRIPTION
**Pull request by patrix1337**
### Fixes

Issue #336 Issue reading column with multiple DATA_PAGE encodings

### Description

Fixed count calculation of already read values.
MergeDictionary() no longer replaces the whole value array.

- [ ] I have included unit tests validating this fix.
- [ ] I have updated markdown documentation where required.

### CODE REVIEW

**Comment by aloneguid** [comment]
It looks good to me. I'd be keen to validate the fix with a test, do you have a sample small parquet file that reproduces the problem? We can simply include it in tests, happy to help.

**Comment by patrix1337** [comment]
Unfortunately I have no small parquet file for testing.

**Comment by aloneguid** [comment]
@patrix1337 is it possible to send one privately?

**Comment by aloneguid** [comment]
closing this as we can't validate the fix

**Pull request closed without merging**
