### PR TITLE
[Merged] Optimize page reading by not creating new array from bytes owner

### PR DESCRIPTION
**Pull request by erchirag**
Optimize page reading by not creating new array from bytes owner

Fixes
Currently for every page read a temporary byte array is created from System.Memory object in BytesOwner. This creation is not required and data can be read directly for existing byte array in which whole page is read.

Issue #
Currently for every page read a temporary byte array is created from System.Memory object in BytesOwner.

 Since this is optimization of existing code, no new unit tests have been added as existing one should be good enough to find any regressions if any
 I have updated markdown documentation where required.
 I understand that successful approval of my pull request requires reproducible tests as per Contribution Guideline.

### CODE REVIEW

**Comment by erchirag** [comment]
Gentle reminder.

**Comment by aloneguid** [comment]
All good, sorry for the delay, I was on holiday to Spain. Oops personal data leaked!

**Comment by aloneguid** [comment]
@erchirag I seem to have lost access to this repo to approve a PR (@azurecoder ?). In the meantime to move you forward I've merged it to my fork at https://github.com/aloneguid/parquet-dotnet and released as v3.4.0 to nuget.org.

**Comment by erchirag** [comment]
Thanks, will probably send more eventually. We are thinking of adding some big features like column indexes, multi page support, dictionary encoding during write but still working out the details internally. I am not sure how much of it would materialize but if you are aware of anyone else also working on similar things, I would love to know more about it.

**Comment by aloneguid** [comment]
@erchirag I'm working on page indexes and dictionary encoding at the moment, ping me ivan@isoloneltd.com to discuss. Dictionary encoding was originally in v2 but was taken out due to stability issues and simplicity of the implementation.

**Comment by erchirag** [comment]
Not sure why but i am not able to reach you on that address , Your message wasn't delivered to ivan@isoloneltd.com because the domain isoloneltd.com couldn't be found. Check for typos or unnecessary spaces and try again.

**Comment by aloneguid** [comment]
Sorry typo ivan@isolineltd.com )

**Pull request merged**
