### PR TITLE
Upgrade visibility of classes, members and fields to allow a custom parquet reader implementation (Issue #296)

### PR DESCRIPTION
**Pull request by dwaijam**
### Fixes

Issue #296 

### Description

Expected behaviour
Certain classes, enums, methods and properties are required to be used if a custom Parquet Reader class needs to be implemented. Some of them are as follows
Thrift/FileMetaData.cs
Thrift/ColumnChunk.cs
Thrift/RowGroup.cs
Parquet/ParquetActor.cs
Parquet/File/ThriftFooter.cs
Parquet/Data/Schema/Field.cs
Parquet/Data/Schema/MapField.cs
Parquet/File/Values/Primitives/Interval.cs
Currently, these are marked as default or internal and need to be made public for them to be accessed outside of the dll.

Actual behaviour
A custom parquet reader cannot be implemented as the required classes are not public.

### Test
Added a simple test to demonstrate the use

### CODE REVIEW

**Comment by dwaijam** [comment]
In the parquet loader implementation that we are working on we don't want / can't store the entire DataSet in memory but want to read the data incrementally, row by row. We also need to buffer an optimum amount of each column chunk so that we don't access the file everytime we access a new row. As such we need access to internal classes. Would you prefer removing the thrift internal classes and adding a reference to a Thrift Nuget package?

**Comment by aloneguid** [comment]
@dwaijam there is no way to access parquet data by rows as it's a columnar format. At the moment you can chunk data by passing `Offset` and `Count` in `ReaderOptions`, will that work?

With regards to Thrift, there is no package available which won't introduce tons of conflicting and unused dependencies on asp.net core, therefore we had to embed only requred parts of Thrift code. Unfortunately Apache community doesn't care/doesn't have enough skills in .NET to confirm PR from us to make only core parts of Thrift available. 

With regards to optimal read performance, we are moving from the idea of row-based `DataSet` in next major version and introduce column streaming instead. We'll still keep it easy to use by allowing to serialise classes directly to Parquet format with some MSIL code generation which makes it super fast, but it's still a few months away from now.

**Comment by dwaijam** [comment]
Yes, ofcourse its a columnar format but we need to implement a RowCursor interface that has a MoveNextRow() method which will be called from upstream for working with parquet files. This needs to be very fast and hence we are caching each rowgroup i.e. all its columnar chunks for only a subset of the columns. Using the ReaderOptions on ParquetReader will be a very heavy operation as it calls Read() method which instantiates a bunch of classes to begin reading. For my implementation, I am instantiating only ColumnarReader object for each column chunk as I move from 1 row group to the next and that's about it. This helps to make it run faster. 

I have used a reference to the Apache Thrift nuget package that you had created - https://www.nuget.org/packages/Apache.Thrift/ and that works for me.

**Comment by aloneguid** [comment]
@dwaijam the biggest overhead in this version is boxing/unboxing which is what we are working on at the moment. This will be solved by better data structures and generating MSIL on the fly.  `ParquetReader` doesn't actually create many classes, it will be the least concern in performance.  You can also limit the columns it reads by passing their names in `ReaderOptions`. I'm not sure opening internals is a good path for this library, it's opening a potential worm hole of instabilities. Is it possible to create something like a `Read` overload that returns only the data you need?

**Comment by azurecoder** [comment]
@dwaijam I think @aloneguid is right. Opening the internals is a bad idea. Parquet is mainly used for big data and columnar distribution. Primary use case is to forego unwanted columns in the execution plan. This implementation is the right one.

**Pull request closed without merging**
