### PR TITLE
code cleanup using JetBrains Rider

### PR DESCRIPTION
**Pull request by ahives**
### Fixes

Issue #

### Description

Minor refactoring to make code more readable. Current tests still pass. No new code was added.

- [ ] I have included unit tests validating this fix.
- [ ] I have updated markdown documentation where required.

### CODE REVIEW

**Comment by aloneguid** [comment]
I see no value in reformatting all the code in default Rider styles. @ahives you can just turn off Rider's style checks if it shows too many warnings, the default style is not an ultimate standard, especially for this project.

**Comment by ahives** [comment]
Well, I was using Rider and made several refactoring by hand. Personally, I see a lot of value in cleaning up code so that it is clearer to people who want to contribute. For example, removing useless private accessors on methods and using new style syntax shorthand like ?: and get => blah I find is very useful.

**Comment by aloneguid** [comment]
@ahives thank you, I appreciate it. However not everyone is using Rider or Resharper and using newest syntax or pleasing jetbrains tools is not this project's goal.

**Comment by ahives** [comment]
I am not affiliated with JetBrains by no means, I was just trying to state what I did. In addition to that you don't need to use Rider to do these refactoring, you can you use plain old Visual Studio. I am not suggesting that the goal of your project is to use the latest tools or anything but I just thought you would want to use more succinct syntax so that more features can get completed faster. By doing this refactoring exercise I actually noticed several algorithm changes that can be made to make the API more performant and potentially reduce errors. Is the expectation to contribute is that everyone write code to a specific coding standard? If so, what is that standard?

**Comment by aloneguid** [comment]
@ahives just wanted to make this slightly clear, apologies for short responses:

1. Tabs/spaces rules and coding style is set by `.editorconfig` in this solution which is supported by all major IDEs/editors, including VS 2017, Rider, IntelliJ IDEA, VS Code etc. It's quite limited in terms of rules and nothing compared to Resharper/Rider, however it's distraction-free and gives people a wider choice of tools.
2. A lot of the code is formatted in a specific way to improve it's understanding which becomes more apparent when you actually start working on it.
3. I'm a big supporter of product quality, tested code and extensible architecture. Rider's way of structuring code (or any other product's) is somewhere at the very bottom of my priorities.
4. I strongly believe that contributing to open source repositories is a culture of adding useful functionality to original codebase, following it's ideas, existing standards and improving functionality. I expect people to follow this approach in current repository and actively doing it myself when changing other's code. I call it "ninja coding" i.e. try to fit in as much as you can, so that your additions are indistinguishable from the original codebase and therefore welcomed and adopted.
5. I find changing code formatting almost rude, as this project is developed 100% in spare time and it's just not nice when people get the latest update with their code reformatted.

Other than that, we always welcome algorithmic and speed  improvements, or contributions of any kind.

**Pull request closed without merging**
