### PR TITLE
78 calculate column stats

### PR DESCRIPTION
**Pull request by azurecoder**
### Fixes

Issue #78 

### Description

Built an adapter pattern to enable counts of nulls, max, min, avg, sd

### Todos
- [ ] unit/integration tests
- [ ] documentation

### CODE REVIEW

**Comment by aloneguid** [comment]
Sorry, not sure we need those. We need stats to choose best encoding for writing, but only plain is implemented and we'll have a better idea what to calculate as this is CPU heavy and may be different for each data type.

**Comment by azurecoder** [comment]
@aloneguid you need to put better, richer descriptions in the issues then! I want this in as it's absolutely relevant to the way that DataFrames measure variance and will be helpful to a number of applications although it should be optional as it's compute intensive to do without an requirement. I'll raise two new issues to make this optional and another to measure "performance statistics" of the column.

**Comment by aloneguid** [comment]
I don't think we should expose this. The problem gets larger when rows are deleted and modified and stats are not updated, making stats "lie". This should be internal to the writer in my opinion. You can achieve the same thing with a linq operator when required.

**Comment by azurecoder** [comment]
I don't agree with this. I don't think that the library should be viewed as a state machine. I think it's the initial programmatic hooks that you put in on #78 that are wrong not the concept. This should be a fundamental part of the reader. DataFrame's in Python and R have the same behaviour all we're doing is pushing this forward so that tools like parq can get access to summary stats. Your description in #78 reflected this activity. The behaviour that I wanted was a lazy behaviour in the reader. It should be calculated then.

**Comment by azurecoder** [comment]
There's another comment about the need for a relevant measurement in #133 which talks about Dictionary Encoding being slightly better but not by much and the best factor being compression due to IO saving so we should talk about whether the write measurements would be useful or not.

**Pull request closed without merging**
